name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Debug - List files
        run: ls -la  # Verify that the file is present

      - name: Run API Tests
        run: newman run DEMOQA.postman_collection.json -e demoqa.postman_environment.json